# Generated by Django 5.2.7 on 2025-11-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('location_at', models.CharField(blank=True, max_length=200, verbose_name='場所')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('category', models.ManyToManyField(blank=True, to='schedule.category', verbose_name='カテゴリー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
